// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ovcnmowwfepquutfopic.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92Y25tb3d3ZmVwcXV1dGZvcGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0MTM4MzUsImV4cCI6MjA0ODk4OTgzNX0.j-ZfYtZ1Ar5BQdtL1cJ9z5YhBHH8lOCpsqUkQo0cn40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);